In [1]:
import numpy as np

In [2]:
arr = np.arange(1,20) # Create a numpy array

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Indexing and slicing using bracket notation

In [4]:
arr[1]

2

In [5]:
arr[3:5]

array([4, 5])

In [6]:
arr[-1]

19

In [7]:
arr[:-3]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Broadcasting

In [8]:
arr[3:5] = 100 # Set arr[3:5] to 100

In [9]:
arr

array([  1,   2,   3, 100, 100,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

__Note__: Slices __point__ to an array rather than do a copy.

In [10]:
smslice = arr[5:9]

In [11]:
arr

array([  1,   2,   3, 100, 100,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

In [12]:
smslice

array([6, 7, 8, 9])

In [13]:
smslice[:] = 23

In [14]:
smslice

array([23, 23, 23, 23])

In [15]:
arr # All elements in smslice set to 23 in arr

array([  1,   2,   3, 100, 100,  23,  23,  23,  23,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

## Indexing multi-dimensional arrays

In [16]:
arr = np.arange(1, 21).reshape(2,10)

In [17]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [18]:
arr[1][1] # Get the second element element from the second array

12

In [19]:
arr[1,1] # Or, Alternatively

12

In [20]:
arr = arr.reshape(5,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [21]:
arr[3,2] # Get the third element from the the 4th row

15

## Slicing multi-dimensional arrays

In [22]:
arr = np.arange(25).reshape(5,5)

In [23]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr[:,:] # Get the whole array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr[:] # Also gets the whole array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr[1:] # Slice every but the 0th row out

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr[1:, 1:] # Slice every but the 0th row and column out

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [28]:
arr[1:3, 2:4] # Slice the first and second row and from that the second and third column

array([[ 7,  8],
       [12, 13]])

### Fancier Indexing and slicing

In [29]:
arr[[3,2,1]] # Get the third, second, and first row in the given order

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [30]:
arr[[1,3],[2,4]] # Get the first and third row only and from them the second and fourth column from them

array([ 7, 19])

### Comparision based selection

In [31]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr[arr<6]

array([0, 1, 2, 3, 4, 5])