In [1]:
import numpy as np

In [2]:
arr = np.arange(21) # [0..20]

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Basic Operations

### Broadcasting
Broadcasting refers to changing the shape of the smaller array in accordance to that of the larger array during arithmetic operations.  
__General Rules:__  
1. Broadcasting takes place element-wise, starting from the trailing dimensions
2. Two dimensions are compatible if:
    - Either they are of the same size or,
    - One of the element is of size 1

In [4]:
arr + 1 # Scalar broadcasting

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [5]:
arr + np.ones(21, dtype=int) # Equivalent to above

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [6]:
arr + arr[1] # Another uninteresting way to do the above

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

__Note__: Numpy throws ValueError when the dimensions of two arrays aren't compatible.

In [7]:
try:
    arr  + (2,3)
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (21,) (2,) 


In [8]:
arr.reshape(7,3) + [10,20,30] # Increment's the three columns by 10,20,30 respectively
                              # since broadcasting works element-wise

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38],
       [19, 30, 41],
       [22, 33, 44],
       [25, 36, 47],
       [28, 39, 50]])

In [9]:
arr * 3 # Multiplication

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60])

In [10]:
2 ** arr # Exponential

array([      1,       2,       4,       8,      16,      32,      64,
           128,     256,     512,    1024,    2048,    4096,    8192,
         16384,   32768,   65536,  131072,  262144,  524288, 1048576])

In [11]:
arr - 3 # Subtraction

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17])

In [12]:
arr % 3 # Modulo

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [13]:
arr / 20 # Division

array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ])

### Matrix operations

#### Matrix Multiplication

In [14]:
arr1 = np.ones((3,3), dtype=int)

In [15]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
arr1 * arr1 # Not matrix multiplication

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
arr1.dot(arr1) # Use dot for matrix multiplication

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

#### Transpose

In [18]:
arr1 = np.random.randint(1,25,size=25).reshape(5,5)

In [19]:
arr1

array([[10,  6,  8,  9, 14],
       [17, 11, 21,  8, 12],
       [17, 20,  9, 15, 11],
       [20, 17,  8,  7, 22],
       [ 3, 16, 17, 12, 17]])

In [20]:
arr1.T # Is a view (pointer rather than copy) can lead to anomalies

array([[10, 17, 17, 20,  3],
       [ 6, 11, 20, 17, 16],
       [ 8, 21,  9,  8, 17],
       [ 9,  8, 15,  7, 12],
       [14, 12, 11, 22, 17]])

In [21]:
arr1 = arr1.T # Works

In [22]:
# arr1 += arr1.T Dangerous on big arrays

#### Get upper and lower triangle

In [23]:
np.triu(arr1) # Elements below primary diagonal are zeroed

array([[10, 17, 17, 20,  3],
       [ 0, 11, 20, 17, 16],
       [ 0,  0,  9,  8, 17],
       [ 0,  0,  0,  7, 12],
       [ 0,  0,  0,  0, 17]])

In [24]:
np.triu(arr1, 1) # Even include primary diagonal

array([[ 0, 17, 17, 20,  3],
       [ 0,  0, 20, 17, 16],
       [ 0,  0,  0,  8, 17],
       [ 0,  0,  0,  0, 12],
       [ 0,  0,  0,  0,  0]])

In [25]:
np.tril(arr1) # For lower trianlge

array([[10,  0,  0,  0,  0],
       [ 6, 11,  0,  0,  0],
       [ 8, 21,  9,  0,  0],
       [ 9,  8, 15,  7,  0],
       [14, 12, 11, 22, 17]])

## Transcedental functions

In [26]:
arr = np.arange(1,21)

In [27]:
np.sin(arr) # Sine of elements

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525])

In [28]:
np.sqrt(arr) # Square root of elements

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595])

In [29]:
np.log(arr) # Log of elements

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509,
        2.39789527,  2.48490665,  2.56494936,  2.63905733,  2.7080502 ,
        2.77258872,  2.83321334,  2.89037176,  2.94443898,  2.99573227])

## Comparisions

In [30]:
arr = np.arange(20)

In [31]:
double_arr = 2 * arr[0:10]
mix_arr = np.concatenate([double_arr, arr[10:20]])

In [32]:
mix_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
mix_arr > arr

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False], dtype=bool)

## Logic operations

In [34]:
ones_arr = np.ones(10, dtype=int)

In [35]:
ones_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
zeros_arr = np.zeros(10, dtype=int)

In [37]:
zeros_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.logical_and(ones_arr, zeros_arr)

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [39]:
np.logical_not(zeros_arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [40]:
np.logical_xor(ones_arr, zeros_arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [41]:
np.any([True, False, True]) # Or

True

In [42]:
np.all([True, False, True]) # And

False

## Reductions

### Computing sum

In [43]:
np.sum(np.arange(20))

190

In [44]:
arr2d = np.arange(20).reshape(4,5)

In [45]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
np.sum(arr2d, axis=1) # Sum of each row

array([10, 35, 60, 85])

In [47]:
np.sum(arr2d, axis=0) # Sum of each column

array([30, 34, 38, 42, 46])

### Other Reductions

In [48]:
np.min(arr2d) # Get min of array

0

In [49]:
np.max(arr2d) # Get max of array

19

In [50]:
np.argmin(arr2d) # Get index of min

0

In [51]:
np.argmax(arr2d) # Get index of max

19

## Statistical Operation

In [52]:
np.mean(arr2d)

9.5

In [53]:
np.median(arr2d)

9.5

In [54]:
arr2d.std()

5.7662812973353983