# Numpy Arrays
Numpy's array are homogenous and multi-dimensional, i.e a table of elements of the __same type__.  
The elements of a numpy array are __indexed__ using a __tuple__ of positive integers.  
The __dimensions__ of a numpy array are called as __axes__, and the number of axes of an array is called its __rank__.

## Casting Python arrays as Numpy Arrays

In [1]:
import numpy as np

In [2]:
# Creating a single dimensional numpy array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# Creating a two dimensional numpy array
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Explicit types
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [5]:
# Explicit dimensions
np.array([1,2,3], ndmin=2) # Creates a two dimensional array

array([[1, 2, 3]])

## Using built-in methods to create numpy array

### numpy.arange
Create an evenly spaced array within a given half-open interval(including start, excluding end).

In [6]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### numpy.zeros and numpy.ones
`numpy.zeros` - Create an array of given shape filled with zeros.  
`numpy.ones`  - Create an array of given shape filled with ones.

In [7]:
np.zeros((2,3)) # A 2 x 3 array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((4,5)) # A 4 x 5 array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### numpy.linspace
Create an array of evenly spaced number over a given interval.  
Not to be confused with numpy.arange which does not necessarily create even spaced integers.

In [9]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

### numpy.eye
Create a 2-D identity matrix.

In [10]:
np.eye(4,5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

### numpy.random
Create array of random numbers.

In [11]:
# numpy.random.rand - 
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
print(np.random.rand(3)) # 1-D
print(np.random.rand(2,2)) # 2-D 

[0.39968691 0.36222669 0.1296895 ]
[[0.62561475 0.96066871]
 [0.73564431 0.04061404]]


In [12]:
# numpy.random.randn - 
# Samples from a normal distribution
np.random.randn(3,3)

array([[ 1.81295216,  0.15824398,  0.34990201],
       [ 0.55108311,  0.52655597,  0.12278228],
       [ 0.98193084, -0.28315957, -1.26631708]])

In [13]:
# numpy.random.randint -
# Generate an array of random integers
np.random.randint(1, 10, 5) # [Start, Stop), Number of samples

array([1, 2, 1, 7, 6])

### np.reshape
Change the shape of an array without changing its data.

In [14]:
arr = np.eye(3,2)

In [15]:
arr

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [16]:
arr.reshape(6,1)

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [17]:
arr.reshape(1,-1)

array([[1., 0., 0., 1., 0., 0.]])

## Properties of numpy arrays

In [18]:
arr = np.random.randint(10, 100, 20).reshape(5, -3)

In [19]:
arr

array([[26, 19, 43, 24],
       [84, 81, 49, 97],
       [23, 14, 36, 35],
       [25, 37, 47, 22],
       [86, 14, 98, 36]])

In [20]:
arr.ndim # Number of dimensions, here 2-D

2

In [21]:
arr.dtype # Type of elements in the array, here int64 

dtype('int64')

In [22]:
arr.shape # Dimension of an array, in (rows, cols), here 5 x 4

(5, 4)

In [23]:
arr.size # Size of arr == reduce(lambda rows, cols: rows * cols, arr.shape)

20

In [24]:
arr.itemsize # Size of each element in the array == arr.dtype.itemsize

8

In [25]:
arr.dtype.itemsize

8